name: C++ Derleyici ve Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Emscripten Hazır Aksiyonu Kullan
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 'latest'

      - name: C++'ı WebAssembly'ye Çevir
        run: |
          # Çıktı adını kesin olarak 'index.js' yapıyoruz
          emcc main.cpp -o index.js -s WASM=1 -s USE_SDL=2 -s ASYNCIFY

      - name: Yayın Klasörünü Hazırla
        run: |
          mkdir public
          cp index.html index.js index.wasm public/
          # Eğer resimlerin/texture'ların varsa onları da kopyala:
          # cp -r assets public/ || true 

      - name: GitHub Pages'a Yükle
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Sadece gerekli dosyaları gönder
